version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.20.6

    working_directory: ~/repo

    steps:
      - checkout

      - run: sudo apt-get update && sudo apt-get install -y libgl1-mesa-dev libx11-dev

      - run: go mod download

      - run: go build -o go-anime-matrix-io

      - store_artifacts:
          path: dist

  package:
    docker:
      - image: cimg/go:1.20.6

    working_directory: ~/repo

    steps:
      - checkout

      - run: sudo apt-get update && sudo apt-get install -y libgl1-mesa-dev libx11-dev

      - run: fyne package -os linux -icon Icon.png

      - store_artifacts:
          path: dist

workflows:
  build-and-package:
    jobs:
      - build
      - package:
          filters:
            branches:
              only: master
          requires:
            - build

  build-only:
    jobs:
      - build
